name: dynamic needs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.step1.outputs.test }}
    steps:
    - id: build
      run: echo "build_status=true" >> "$GITHUB_OUTPUT"

  build_success:
    needs: build
    if: needs.build.outputs.build_status
    runs-on: ubuntu-latest
    steps:
    - run: echo build success

  build_failure:
    needs: build
    if: ! needs.build.outputs.build_status
    runs-on: ubunu-latest
    steps:
    - run: echo build failure
