name: dynamic needs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build.outputs.build_status }}
    steps:
    - id: build
      run: echo "build_status=true" >> "$GITHUB_OUTPUT"

  build_success:
    needs: build
    if: needs.build.outputs.build_status == 'true'
    runs-on: ubuntu-latest
    steps:
    - run: echo build success

  build_failure:
    needs: build
    if: needs.build.outputs.build_status == 'false'
    runs-on: ubunu-latest
    steps:
    - run: echo build failure
